### PR TITLE
Diagram

### PR DESCRIPTION
**Pull request by jobanputra**
Updated spelling mistake
Removed docker
Added kubelet
No red squiggly line showing.

### CODE REVIEW

**Comment by jobanputra** [comment]
I had kube-proxy to an earlier version of the diagram. The feedback from @aaron-schnieder was to remove it.

**Comment by aaron-schnieder** [comment]
I guess I don't see the value in showing the kube-system objects at all. Those are better described in actual k8 documentation. I see the value is showing specifics of how the resources are setup in the Azure cluster, because that is dictated by the reference solution. We can discuss.

**Comment by billpratt** [comment]
@aaron-schnieder That makes sense. Maybe for this diagram we remove the kube resources and replace with "Kubernetes Master" and "Kubernetes Node". In the k8s diagram we can then list out the components.

**Comment by aaron-schnieder** [comment]
Agreed.

**Comment by aaron-schnieder** [comment]
@jobanputra are you making changes so we can close out this PR?

**Comment by jobanputra** [comment]
@billpratt @aaron-schnieder Updated based on feedback.

**Pull request merged**
