### PR TITLE
removing configmap deployment from script

### PR DESCRIPTION
**Pull request by elizabethhalper**

### CODE REVIEW

**Comment by elizabethhalper** [comment]
@billpratt that line is no longer in there on this branch. I'm assuming you're referring to the line with MT_CONNECTION_STRING?

**Comment by billpratt** [comment]
Yes, all references to MT_CONNECTION_STRING should be removed. You may not have the latest from master. Make sure to pull that in and remove that line.

**Comment by elizabethhalper** [comment]
@billpratt okay thanks, I made sure there were no references to MT_CONNECTION_STRING in this branch and have merged in the updated master

**Comment by elizabethhalper** [comment]
@billpratt sorry about that. its all fixed now

**Pull request merged**
